"""Agent 002: Wizardset Example Generator.

This agent creates beginner-friendly examples for every Wizardset function.
It is designed to support README expansion, teaching notes, and future docs.
"""

from __future__ import annotations

from agents.common import (
    BASIC_EXAMPLES,
    DINOSAUR_EXAMPLES,
    FUNCTION_EXPLANATIONS,
    top_level_functions,
    write_report,
)


REPORT_NAME = "beginner_examples.md"


def build_examples_report() -> str:
    """Build a markdown file of examples for all Wizardset functions."""
    functions = top_level_functions()

    lines: list[str] = []
    lines.append("# Wizardset Beginner Examples")
    lines.append("")
    lines.append("These examples are generated by the local Wizardset Example Generator agent.")
    lines.append("They are meant to help learners understand what each helper function teaches.")
    lines.append("")

    lines.append("## Tiny dataset used for dinosaur-style examples")
    lines.append("")
    lines.append("```python")
    lines.append("dinosaurs = [")
    lines.append("    {'name': 'Velociraptor', 'mass_kg': 15, 'speed_kmh': 40, 'diet': 'carnivore', 'era': 'Cretaceous', 'length_m': 2, 'intelligence_score': 8},")
    lines.append("    {'name': 'Triceratops', 'mass_kg': 6000, 'speed_kmh': 25, 'diet': 'herbivore', 'era': 'Cretaceous', 'length_m': 9, 'intelligence_score': 5},")
    lines.append("    {'name': 'Tyrannosaurus', 'mass_kg': 8000, 'speed_kmh': 27, 'diet': 'carnivore', 'era': 'Cretaceous', 'length_m': 12, 'intelligence_score': 7},")
    lines.append("]")
    lines.append("```")
    lines.append("")

    for name in functions:
        lines.append(f"## `{name}()`")
        lines.append("")
        lines.append(FUNCTION_EXPLANATIONS.get(name, "No explanation added yet."))
        lines.append("")
        lines.append("### Basic example")
        lines.append("```python")
        lines.append(BASIC_EXAMPLES.get(name, f"# Add a basic example for {name}()"))
        lines.append("```")
        lines.append("")
        lines.append("### Dinosaur example")
        lines.append("```python")
        lines.append(DINOSAUR_EXAMPLES.get(name, f"# Add a dinosaur example for {name}()"))
        lines.append("```")
        lines.append("")

    lines.append("## Suggested README use")
    lines.append("")
    lines.append("Use the strongest examples from this file in the README, keeping the README short and linking to fuller docs later.")

    return "\n".join(lines)


def main() -> None:
    """Run the example generator."""
    path = write_report(REPORT_NAME, build_examples_report())
    print(f"Examples report created: {path}")


if __name__ == "__main__":
    main()
